
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.3b1'
version_full = 'f404e4abc426ce08850283345ce162fb9b5403cf'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
