
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.3'
version_full = 'f17f8c43e217b65a951e5db357699c2d2af6098f'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
